### ISSUE TITLE
edge-http won't compile with `embassy-futures v0.1.2`

### ISSUE THREAD

**Issue by AnthonyGrondin** [sysgrok/edge-net#74]
`embassy-futures v0.1.1 -> v0.1.2` is breaking due to https://github.com/embassy-rs/embassy/pull/3328 which fixed a soundness issue, which affects the inner workings of `edge-http`.

Compiling with `embassy-futures@v0.1.2` will produce the following compilation error:

```
error[E0308]: mismatched types
   --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/edge-http-0.6.0/src/io/server.rs:749:65
    |
718 |                 .push(async move {
    |                       ---------- the found `async` block
...
749 |         let (result, _) = embassy_futures::select::select_slice(&mut tasks).await;
    |                           ------------------------------------- ^^^^^^^^^^ expected `Pin<&mut [_]>`, found `&mut Vec<..., P>`
    |                           |
    |                           arguments to this function are incorrect
    |
    = note:         expected struct `Pin<&mut [_]>`
            found mutable reference `&mut Vec<{async block@~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/edge-http-0.6.0/src/io/serve
r.rs:718:23: 718:33}, P>`
note: function defined here
   --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-futures-0.1.2/src/select.rs:523:8
    |
523 | pub fn select_slice<'a, Fut: Future>(slice: Pin<&'a mut [Fut]>) -> SelectSlice<'a, Fut> {
    |        ^^^^^^^^^^^^


```
